import sys,json; sys.path.insert(0,"/home/josechavez/persona_es/scripts")
from wf_chunk import O
DICT={
"<FF03>This ain't fair.":"<FF03>No es justo.",
"The machine seems to be out of order!":"La maquina parece estar averiada!",
"You currently have":"Actualmente tienes",
"You have":"Tienes",
"coins!":"fichas!",
"It's a video poker machine!":"Es una maquina de video poker!",
"What will you do?":"Que haras?",
"What would you like explained?":"Que quieres que te explique?",
"In this version of poker, you can<FF03>change your hand once!":"En esta version de poker, puedes<FF03>cambiar tu mano una vez!",
"You will be dealt five cards at the<FF03>outset!":"Recibiras cinco cartas al<FF03>inicio!",
"Use the directional buttons to move to<FF03>a card, and press the":"Usa los botones de direccion para ir a<FF03>una carta, y presiona el",
"buttons<FF03>to hold that card!":"botones<FF03>para retener esa carta!",
"Once you have chosen which cards to<FF03>hold, press the R button to re-draw<FF03>the remaining cards!":"Cuando elijas que cartas<FF03>retener, presiona R para repartir<FF03>las cartas restantes!",
"If you have a valid hand after the<FF03>second draw, you win!":"Si tienes una mano valida tras el<FF03>segundo reparto, ganas!",
"The higher the bet, the larger the<FF03>payout for a winning hand will be!":"Mientras mayor la apuesta, mayor el<FF03>pago por una mano ganadora!",
"If you win, you can bet the amount<FF03>you just won on an Extra Game!":"Si ganas, puedes apostar lo que<FF03>ganaste en un Juego Extra!",
"If you'd rather not risk it, choose<FF03>":"Si no quieres arriesgarlo, elige<FF03>",
"Take Winnings!":"Tomar Ganancias!",
"There are three types of Extra Game!<FF03>Each round you win doubles your<FF03>earnings!":"Hay tres tipos de Juego Extra!<FF03>Cada ronda ganada duplica tus<FF03>ganancias!",
"By winning the Extra Game, you can<FF03>wager up to 1,000,000 coins!":"Al ganar el Juego Extra, puedes<FF03>apostar hasta 1,000,000 fichas!",
"But be careful":"Pero cuidado",
"one mistake and you'll<FF03>lose it all!":"un error y lo<FF03>perderas todo!",
"Extra Game 1":"Juego Extra 1",
"Extra Game 2":"Juego Extra 2",
"Extra Game 3":"Juego Extra 3",
"High":"Alto",
"Low!":"Bajo!",
"Low":"Bajo",
"One card is shown, with four other<FF03>cards left face-down!":"Se muestra una carta, con otras cuatro<FF03>boca abajo!",
"You must guess which face-down card is<FF03>higher than the shown card!":"Adivina cual carta oculta es<FF03>mayor que la mostrada!",
"If the card you draw has the same<FF03>number as the shown card, the game is<FF03>a draw and you may try again!":"Si la carta que sacas tiene el mismo<FF03>numero que la mostrada, hay<FF03>empate y puedes intentar de nuevo!",
"Big":"Mayor",
"Small!":"Menor!",
"Small":"Menor",
"One card is shown and one card is<FF03>face-down!":"Se muestra una carta y otra esta<FF03>boca abajo!",
"You must guess whether the face-down<FF03>card is bigger or smaller than the<FF03>shown card!":"Adivina si la carta oculta es<FF03>mayor o menor que la<FF03>mostrada!",
"If both cards are equal, you lose,<FF03>so be careful!":"Si ambas cartas son iguales, pierdes,<FF03>asi que cuidado!",
"One face-down card is dealt!":"Se reparte una carta boca abajo!",
"If you think it's":"Si crees que es",
", choose Red!":", elige Rojo!",
", choose Black!":", elige Negro!",
"Red":"Rojo",
"Black!":"Negro!",
"Black":"Negro",
"If the color you chose matches the<FF03>card's color, you win!":"Si el color que elegiste coincide con<FF03>el de la carta, ganas!",
"Before normal play":"Antes del juego normal",
"<FF03>Enters one coin!":"<FF03>Mete una ficha!",
"During normal play":"Durante el juego normal",
"<FF03>Hold or un-hold a card!":"<FF03>Reten o suelta una carta!",
"After winning hand":"Tras mano ganadora",
"<FF03>Try the Extra Game High":"<FF03>Juega el Extra Alto",
"During Extra Game":"Durante Juego Extra",
"<FF03>Select a card to turn over!":"<FF03>Elige una carta para voltear!",
"After winning Extra Game":"Tras ganar Juego Extra",
"<FF03>Bet your winnings on another try!":"<FF03>Apuesta tus ganancias otra vez!",
"<FF03>Cancel a coin that's been bet!":"<FF03>Cancela una ficha apostada!",
"<FF03>Decline the Extra Game and collect<FF03>your winnings!":"<FF03>Rechaza el Juego Extra y cobra<FF03>tus ganancias!",
"<FF03>End the Extra Game and collect your<FF03>winnings!":"<FF03>Termina el Juego Extra y cobra tus<FF03>ganancias!",
"<FF03>Bet the maximum total possible!":"<FF03>Apuesta el maximo total posible!",
"<FF03>Try the Extra Game Big":"<FF03>Juega el Extra Mayor",
"<FF03>Not used!":"<FF03>No se usa!",
"<FF03>Try the Extra Game Red":"<FF03>Juega el Extra Rojo",
"R button":"boton R",
"L button":"boton L",
"<FF03>Starts the game if a bet has been placed!":"<FF03>Inicia el juego si hay apuesta!",
"<FF03>Re-draw cards that are not being held!":"<FF03>Reparte las cartas no retenidas!",
"<FF03>Ends the game!":"<FF03>Termina el juego!",
"Directional buttons":"Botones de direccion",
"<FF03>Select cards!":"<FF03>Elige cartas!",
"<FF03>Select a card!":"<FF03>Elige una carta!",
"Two pair":"Par doble",
"<FF03>Two sets of two cards of the same<FF03>number!":"<FF03>Dos pares de cartas del mismo<FF03>numero!",
"Three of a kind":"Trio",
"<FF03>A set of three cards of the same<FF03>number!":"<FF03>Tres cartas del mismo<FF03>numero!",
"Straight flush":"Escalera de color",
"<FF03>A Straight with all five cards in<FF03>the same suit!":"<FF03>Una escalera con las cinco cartas<FF03>del mismo palo!",
"Straight":"Escalera",
"<FF03>Five numbers in sequence, of any suit!":"<FF03>Cinco numeros en secuencia, cualquier palo!",
"Full house":"Full",
"<FF03>Three of a kind together with a pair!":"<FF03>Un trio junto con un par!",
"Four of a kind":"Poker",
"<FF03>A set of four cards of the same<FF03>number!":"<FF03>Cuatro cartas del mismo<FF03>numero!",
"Five of a kind":"Quintilla",
"<FF03>Four of a kind with a Joker for the<FF03>fifth card!":"<FF03>Cuatro iguales con un Joker de<FF03>quinta carta!",
"Royal flush":"Escalera real",
"<FF03>A straight flush with 10-J-Q-K-A!":"<FF03>Una escalera de color 10-J-Q-K-A!",
"Flush":"Color",
"<FF03>Five cards of the same suit!":"<FF03>Cinco cartas del mismo palo!",
"Special cases":"Casos especiales",
"-In this version of poker, a pair is<FF03>not a winning hand!":"-En esta version, un par no<FF03>es mano ganadora!",
"-In a straight, an ace is not lower<FF03>than a 2!":"-En escalera, el as no es menor<FF03>que un 2!",
"-The Joker is a wild card that can be<FF03>used as part of any winning hand!":"-El Joker es comodin y sirve<FF03>en cualquier mano ganadora!",
"It's a video blackjack machine!":"Es una maquina de video blackjack!",
"This is a one-on-one-game of blackjack<FF03>against the dealer!":"Es un blackjack uno a uno<FF03>contra el crupier!",
"The computer acts as the dealer!":"La computadora es el crupier!",
"Two cards are dealt to the player and<FF03>the dealer at the outset!":"Se reparten dos cartas al jugador y<FF03>al crupier al inicio!",
"One of the dealer's two cards will be<FF03>kept face-down!":"Una de las cartas del crupier queda<FF03>boca abajo!",
"If the dealer's shown card is an ace,<FF03>you may place an insurance bet!":"Si la carta visible del crupier es as,<FF03>puedes apostar un seguro!",
"The insurance mechanic will be explained<FF03>at the end of these rules!":"El seguro se explica<FF03>al final de estas reglas!",
"First, compare your cards to the dealer's<FF03>to decide whether to draw another card!":"Primero, compara tus cartas con las del<FF03>crupier para decidir si pides otra!",
"If you decide to draw, select Hit!<FF03>If not, select Stand!":"Si decides pedir, elige Pedir!<FF03>Si no, elige Plantarte!",
"You may draw up to 7 cards as long as<FF03>their total value remains 21 or lower!":"Puedes pedir hasta 7 cartas mientras<FF03>su valor total sea 21 o menos!",
"The following circumstances will result<FF03>in an automatic Stand":"Las siguientes situaciones causan<FF03>un Plante automatico",
"-Your initial draw is blackjack!":"-Tu reparto inicial es blackjack!",
"-The total of the cards drawn after<FF03>Hitting is 21!":"-El total de las cartas tras<FF03>Pedir es 21!",
"-You draw seven cards!":"-Sacas siete cartas!",
"-The cards' total value surpasses 21,<FF03>resulting in a bust!":"-El valor total supera 21,<FF03>te pasas!",
"2 through 10 are face value! J through<FF03>K are worth 10, and A is worth either<FF03>1 or 11!":"2 a 10 valen su numero! J a<FF03>K valen 10, y el A vale<FF03>1 u 11!",
"After the player Stands, the dealer<FF03>will draw cards!":"Tras plantarte el jugador, el crupier<FF03>saca cartas!",
"If your total is larger than the<FF03>dealer's without surpassing 21":"Si tu total es mayor que el del<FF03>crupier sin pasar de 21",
"<FF03>If you have blackjack of A and J<FF03>and the cards' suit is":"<FF03>Si tienes blackjack de A y J<FF03>y el palo de las cartas es",
"<FF03>When both initial cards are 7s and you<FF03>draw a third 7 after Hitting!":"<FF03>Cuando ambas cartas iniciales son 7 y<FF03>sacas un tercer 7 al Pedir!",
"It's a slot machine!":"Es una tragamonedas!",
"This slot machine consists of 5<FF03>big reels and 16 small reels!":"Esta tragamonedas tiene 5<FF03>rodillos grandes y 16 chicos!",
"The number of ways to line up a win<FF03>increases with the size of your bet!":"Las formas de alinear un premio<FF03>aumentan con tu apuesta!",
"You can bet up to 8 coins!":"Puedes apostar hasta 8 fichas!",
"Bets 1, 2, 5, and 6 are for the<FF03>horizontal lines,while 3, 4, 7,<FF03>and 8 are for the vertical lines!":"Apuestas 1, 2, 5 y 6 son para las<FF03>lineas horizontales, y 3, 4, 7,<FF03>y 8 para las verticales!",
"Bets 1, 2, 5, and 6 are for the<FF03>horizontal lines,while 3, 4, 4, 7,<FF03>and 8 are for the vertical lines!":"Apuestas 1, 2, 5 y 6 son para las<FF03>lineas horizontales, y 3, 4, 4, 7,<FF03>y 8 para las verticales!",
"Bets 5 through 8 also add two ways<FF03>to line up a win per bet!":"Apuestas 5 a 8 anaden dos formas<FF03>de ganar por apuesta!",
"When the game begins, the big and small<FF03>reels will all start to spin!":"Al empezar, los rodillos grandes y<FF03>chicos giran todos!",
"Once the reels have spun enough,<FF03>the small reels will stop!":"Cuando giren bastante,<FF03>los rodillos chicos paran!",
"The big<FF03>reels will continue to spin!":"Los rodillos<FF03>grandes siguen girando!",
"Press the":"Presiona los",
", and":", y",
"buttons to<FF03>rotate the corresponding reels!":"botones para<FF03>girar los rodillos correspondientes!",
"Adjust the small reels so that it will<FF03>be easier to line up a pattern!":"Ajusta los rodillos chicos para que<FF03>sea mas facil alinear un patron!",
"When you have finished, press the<FF03>R button to stop the big reels!":"Cuando termines, presiona el<FF03>boton R para parar los grandes!",
"If three or more of a symbol are lined<FF03>up along one of your bets, you win!":"Si tres o mas simbolos se alinean<FF03>en una de tus apuestas, ganas!",
"Up to five symbols can cross bets 1<FF03>through 4, and up to four can cross<FF03>bets 5 through 8!":"Hasta cinco simbolos cruzan apuestas 1<FF03>a 4, y hasta cuatro cruzan<FF03>apuestas 5 a 8!",
"When the symbols on the big reels match<FF03>diagonally, in all four corners, or all<FF03>five at once":"Cuando los simbolos grandes coinciden<FF03>en diagonal, en las cuatro esquinas, o<FF03>los cinco a la vez",
"You win regardless of which lines you<FF03>bet on!":"Ganas sin importar en que lineas<FF03>apostaste!",
"Earnings for hits on the big reels<FF03>increase according to the number of<FF03>bets you made!":"Las ganancias en los rodillos grandes<FF03>suben segun el numero de<FF03>apuestas que hiciste!",
"Before starting":"Antes de empezar",
"<FF03>Add a coin!":"<FF03>Anade una ficha!",
"During play":"Durante el juego",
"<FF03>Rotate the four small reels to the<FF03>bottom!":"<FF03>Gira los cuatro rodillos chicos<FF03>abajo!",
"<FF03>Remove a coin!":"<FF03>Quita una ficha!",
"<FF03>Rotate the four small reels to the<FF03>right!":"<FF03>Gira los cuatro rodillos chicos<FF03>a la derecha!",
"<FF03>Rotate the four small reels to the top!":"<FF03>Gira los cuatro rodillos chicos arriba!",
"<FF03>Rotate the four small reels to the left!":"<FF03>Gira los cuatro rodillos a la izquierda!",
"<FF03>Stop the big reels!":"<FF03>Para los rodillos grandes!",
"Different slot machines have different<FF03>patterns and odds!":"Distintas tragamonedas tienen distintos<FF03>patrones y probabilidades!",
"It's best to try out different machines<FF03>rather than concentrating on one!":"Mejor probar varias maquinas<FF03>en vez de concentrarse en una!",
"Be careful not to forget to rotate the<FF03>small reels during the game!":"Cuidado de no olvidar girar los<FF03>rodillos chicos durante el juego!",
"Careful adjustment of the small reels<FF03>is key to maximizing your payout!":"Ajustar bien los rodillos chicos<FF03>es clave para maximizar tu pago!",
"If you begin the game with fewer bets,<FF03>you may face greater losses when it<FF03>matters most!":"Si empiezas con pocas apuestas,<FF03>puedes tener mayores perdidas cuando<FF03>mas importa!",
"For best results, always play the game<FF03>with the full eight bets!":"Para mejores resultados, juega siempre<FF03>con las ocho apuestas!",
"It's a video dice game!":"Es un juego de dados!",
"In this game, two dice are rolled on<FF03>screen, and you predict the outcome!":"Aqui se lanzan dos dados en<FF03>pantalla, y predices el resultado!",
"You can bet on eleven rolls, from 2<FF03>to 12, and you may bet on as many rolls<FF03>per game as you wish!":"Puedes apostar a once tiradas, de 2<FF03>a 12, y a cuantas tiradas<FF03>quieras por juego!",
"However, you may bet a maximum of 100<FF03>coins on any given roll!":"Pero puedes apostar maximo 100<FF03>fichas por tirada!",
"If you bet on the correct roll, a<FF03>multiplier determines your winnings!":"Si aciertas la tirada, un<FF03>multiplicador define tu premio!",
"You can also stake your winnings on<FF03>an Extra Game!":"Tambien puedes apostar tus ganancias<FF03>en un Juego Extra!",
"In the Extra Game, you do not predict<FF03>the outcome of the roll":"En el Juego Extra, no predices<FF03>el resultado de la tirada",
"<FF03>Instead, any roll other than 7 wins!":"<FF03>En cambio, cualquier tirada salvo 7 gana!",
"The amount you win differs depending on<FF03>the roll!":"El monto que ganas varia segun<FF03>la tirada!",
"If the roll is 7, the Extra Game ends<FF03>and all your winnings are lost, so be<FF03>careful!":"Si sale 7, el Juego Extra termina<FF03>y pierdes todo lo ganado, asi que<FF03>cuidado!",
"<FF03>Add 10 coins to the bet at the cursor!":"<FF03>Anade 10 fichas a la apuesta del cursor!",
"After winning the Extra Game":"Tras ganar el Juego Extra",
"After winning":"Tras ganar",
"<FF03>Try the Extra Game again!":"<FF03>Juega el Juego Extra otra vez!",
"<FF03>Try the Extra Game!":"<FF03>Juega el Juego Extra!",
"<FF03>Remove all coins at the cursor!":"<FF03>Quita todas las fichas del cursor!",
"<FF03>Add 100 coins to the bet at the cursor!":"<FF03>Anade 100 fichas a la apuesta del cursor!",
"<FF03>Reset bet amount to 0 coins!":"<FF03>Reinicia la apuesta a 0 fichas!",
"<FF03>Select the rolls to bet on!":"<FF03>Elige las tiradas a apostar!",
"The closer the roll is to 7, the lower<FF03>the multiplier! This is because rolls<FF03>close to 7 appear more frequently!":"Mientras mas cerca de 7, menor<FF03>el multiplicador! Porque las tiradas<FF03>cerca de 7 salen mas seguido!",
"Thus, the safe bet is on rolls close<FF03>to 7, with rolls like 2 and 12 being<FF03>riskier!":"Asi, lo seguro es apostar cerca<FF03>de 7, y tiradas como 2 y 12 son<FF03>mas riesgosas!",
"In the Extra Game, if a roll of 7<FF03>comes up, you lose all your winnings!":"En el Juego Extra, si sale 7,<FF03>pierdes todas tus ganancias!",
"The trick to not losing too much is<FF03>not to get greedy and leave with a<FF03>reasonable amount!":"El truco para no perder mucho es<FF03>no ser codicioso y salir con un<FF03>monto razonable!",
"Metal Cards!":"Cartas Metal!",
"It's a Code Breaker machine!":"Es una maquina Code Breaker!",
"In this game, the numbers 1 through 9<FF03>are dispersed throughout a grid!":"Aqui los numeros 1 al 9<FF03>se reparten en una cuadricula!",
"Your goal is to guess the arrangement<FF03>of the numbers!":"Tu meta es adivinar el orden<FF03>de los numeros!",
"The fewer tries it takes, the better<FF03>the prize you receive!":"Cuantos menos intentos, mejor<FF03>el premio que recibes!",
"If you cannot crack it in 8 tries,<FF03>the game ends!":"Si no lo logras en 8 intentos,<FF03>el juego termina!",
"The Result to the left of the screen<FF03>shows your previous attempts!":"El Resultado a la izquierda<FF03>muestra tus intentos previos!",
"If you guess incorrectly, the guess<FF03>will be displayed in the Results!":"Si fallas, la conjetura<FF03>se muestra en los Resultados!",
"Use it as a reference when formulating<FF03>your next guess!":"Usalo de referencia al formular<FF03>tu siguiente conjetura!",
"The Chosen display at the top shows<FF03>the numbers in use!":"La pantalla Elegidos arriba muestra<FF03>los numeros en uso!",
"All numbers, 1 through 9, must be used<FF03>in the code!":"Todos los numeros, 1 al 9, se usan<FF03>en el codigo!",
"Use the Chosen display to see which<FF03>numbers are missing from your guess!":"Usa la pantalla Elegidos para ver que<FF03>numeros faltan en tu conjetura!",
"This game accepts":"Este juego acepta",
"Metal Cards":"Cartas Metal",
"instead<FF03>of coins!":"en vez<FF03>de fichas!",
"<FF03>Decreases the selected number!":"<FF03>Disminuye el numero elegido!",
"<FF03>Marks the selected number by changing<FF03>its color!":"<FF03>Marca el numero elegido cambiando<FF03>su color!",
"Use this to mark numbers you know are<FF03>correct!":"Usalo para marcar numeros que sabes<FF03>correctos!",
"<FF03>Increases the selected number!":"<FF03>Aumenta el numero elegido!",
"<FF03>Inserts 1 Metal Card to start the game!":"<FF03>Mete 1 Carta Metal para iniciar!",
"<FF03>Moves the cursor!":"<FF03>Mueve el cursor!",
"H indicates how many exact matches<FF03>are in a row":"H indica cuantas coincidencias exactas<FF03>hay en una fila",
"column!":"columna!",
"B shows how many numbers belong in<FF03>that row":"B muestra cuantos numeros van en<FF03>esa fila",
"column, but not in their<FF03>present position!":"columna, pero no en su<FF03>posicion actual!",
"The key to the game is to determine<FF03>where a hit":"La clave es determinar<FF03>donde un acierto",
"is on both the row<FF03>and the column!":"esta en la fila<FF03>y la columna!",
"It's best to mark places where both<FF03>the row and the column are hits!":"Mejor marcar donde tanto<FF03>la fila como la columna aciertan!",
"The Results of your previous guesses<FF03>can also be useful hints!":"Los Resultados de tus conjeturas<FF03>previas tambien dan pistas utiles!",
"Clerk<FF03>Wanna see what I've got?":"Mozo<FF03>Quieres ver lo que tengo?",
"Customer<FF03>Rumor has it that the girl in black<FF03>grants any wish you want!":"Cliente<FF03>Dicen que la chica de negro<FF03>cumple cualquier deseo!",
"button":"boton",
"Button":"Boton",
}
ids=['e2_00285','e2_00286','e2_00293','e2_00294','e2_00295','e2_00636','e2_00637','e2_00644','e2_00645','e2_00646','e2_00656','e2_00657','e2_00664','e2_00665','e2_00666','e2_01102','e2_01103','e2_01110','e2_01111','e2_01112','e2_01239','e2_01240','e2_01247','e2_01248','e2_01249','e2_01381','e2_01389','e2_01391']
pairs=sorted(DICT.items(), key=lambda kv:-len(kv[0]))  # longest first
m={}
for i in ids:
    s=O(i)
    for en,es in pairs:
        s=s.replace(en,es)
    m[i]={"t":s,"shortened":True}
json.dump(m,open("/home/josechavez/persona_es/translated_text/_wfmaps/e2_casino.json","w",encoding="utf-8"),ensure_ascii=False,indent=1)
print("dict size",len(DICT),"-> map",len(m))
