import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
import wf_chunk_e0 as W

# Master casino phrase dictionary. Long/specific phrases first, generic short last.
PAIRS = [
    ("<FF1B>Clerk<FF03>Wanna see what I've got?", "<FF1B>Clerk<FF03>Quieres ver lo que tengo?"),
    ("The machine seems to be out of order!", "La maquina parece descompuesta!"),
    # poker intro
    ("In this version of poker, you can<FF03>change your hand once!", "En esta version de poker, puedes<FF03>cambiar tu mano una vez!"),
    ("You will be dealt five cards at the<FF03>outset!", "Se te reparten cinco cartas al<FF03>inicio!"),
    ("Use the directional buttons to move to<FF03>a card, and press the ", "Usa los botones de direccion para ir a<FF03>una carta, y pulsa el "),
    ("buttons<FF03>to hold that card!", "botones<FF03>para conservar esa carta!"),
    ("Once you have chosen which cards to<FF03>hold, press the R button to re-draw<FF03>the remaining cards!", "Cuando elijas que cartas<FF03>conservar, pulsa R para repartir<FF03>las cartas restantes!"),
    ("If you have a valid hand after the<FF03>second draw, you win!", "Si tienes mano valida tras el<FF03>segundo reparto, ganas!"),
    ("The higher the bet, the larger the<FF03>payout for a winning hand will be!", "A mayor apuesta, mayor sera el<FF03>pago por una mano ganadora!"),
    ("If you win, you can bet the amount<FF03>you just won on an Extra Game!", "Si ganas, puedes apostar lo que<FF03>ganaste en un Juego Extra!"),
    ("If you'd rather not risk it, choose<FF03><0028>Take Winnings!<0028>", "Si no quieres arriesgarlo, elige<FF03><0028>Tomar Ganancias!<0028>"),
    ("There are three types of Extra Game!", "Hay tres tipos de Juego Extra!"),
    ("Each round you win doubles your<FF03>earnings!", "Cada ronda ganada duplica tus<FF03>ganancias!"),
    ("By winning the Extra Game, you can<FF03>wager up to 1,000,000 coins!", "Al ganar el Juego Extra, puedes<FF03>apostar hasta 1,000,000 monedas!"),
    ("But be careful<0007> one mistake and you'll<FF03>lose it all!", "Pero cuidado<0007> un error y lo<FF03>perderas todo!"),
    ("One card is shown, with four other<FF03>cards left face-down!", "Se muestra una carta y otras cuatro<FF03>quedan boca abajo!"),
    ("You must guess which face-down card is<FF03>higher than the shown card!", "Debes adivinar que carta oculta es<FF03>mayor que la mostrada!"),
    ("If the card you draw has the same<FF03>number as the shown card, the game is<FF03>a draw and you may try again!", "Si la carta sacada tiene el mismo<FF03>numero que la mostrada, hay<FF03>empate y puedes reintentar!"),
    ("One card is shown and one card is<FF03>face-down!", "Se muestra una carta y otra queda<FF03>boca abajo!"),
    ("You must guess whether the face-down<FF03>card is bigger or smaller than the<FF03>shown card!", "Debes adivinar si la carta oculta<FF03>es mayor o menor que la<FF03>mostrada!"),
    ("If both cards are equal, you lose,<FF03>so be careful!", "Si ambas cartas son iguales, pierdes,<FF03>ten cuidado!"),
    ("One face-down card is dealt!", "Se reparte una carta boca abajo!"),
    ("If you think it's <0204> or <0205>, choose Red!", "Si crees que es <0204> o <0205>, elige Rojo!"),
    ("If you think it's <0206> or <0207>, choose Black!", "Si crees que es <0206> o <0207>, elige Negro!"),
    ("If the color you chose matches the<FF03>card's color, you win!", "Si el color elegido coincide con<FF03>el de la carta, ganas!"),
    ("<0043>Extra Game 1<0044>", "<0043>Juego Extra 1<0044>"),
    ("<0043>Extra Game 2<0044>", "<0043>Juego Extra 2<0044>"),
    ("<0043>Extra Game 3<0044>", "<0043>Juego Extra 3<0044>"),
    ("<0005>High <0055> Low", "<0005>Alta <0055> Baja"),
    ("<0005>Big <0055> Small", "<0005>Grande <0055> Chica"),
    ("<0005>Red <0055> Black", "<0005>Rojo <0055> Negro"),
    ("Try the Extra Game High <0055> Low!", "Prueba el Juego Extra Alta <0055> Baja!"),
    ("Try the Extra Game Big <0055> Small!", "Prueba el Juego Extra Grande <0055> Chica!"),
    ("Try the Extra Game Red <0055> Black!", "Prueba el Juego Extra Rojo <0055> Negro!"),
    ("Bet your winnings on another try!", "Apuesta tus ganancias en otro intento!"),
    ("Cancel a coin that's been bet!", "Cancela una moneda apostada!"),
    ("Decline the Extra Game and collect<FF03>your winnings!", "Rechaza el Juego Extra y cobra<FF03>tus ganancias!"),
    ("End the Extra Game and collect your<FF03>winnings!", "Termina el Juego Extra y cobra tus<FF03>ganancias!"),
    ("Enters one coin!", "Mete una moneda!"),
    ("Hold or un-hold a card!", "Conserva o suelta una carta!"),
    ("Re-draw cards that are not being held!", "Reparte las cartas no conservadas!"),
    ("Select a card to turn over!", "Elige una carta para voltear!"),
    # poker hands (<0006> variant)
    ("Two pair<0006><FF03>Two sets of two cards of the same<FF03>number!", "Doble par<0006><FF03>Dos pares de cartas del mismo<FF03>numero!"),
    ("Three of a kind<0006><FF03>A set of three cards of the same<FF03>number!", "Trio<0006><FF03>Tres cartas del mismo<FF03>numero!"),
    ("Straight<0006><FF03>Five numbers in sequence, of any suit!", "Escalera<0006><FF03>Cinco numeros seguidos, de cualquier palo!"),
    ("Flush<0006><FF03>Five cards of the same suit!", "Color<0006><FF03>Cinco cartas del mismo palo!"),
    ("Full house<0006><FF03>Three of a kind together with a pair!", "Full<0006><FF03>Un trio junto con un par!"),
    ("Four of a kind<0006><FF03>A set of four cards of the same<FF03>number!", "Poker<0006><FF03>Cuatro cartas del mismo<FF03>numero!"),
    ("Straight flush<0006><FF03>A Straight with all five cards in<FF03>the same suit!", "Escalera de color<0006><FF03>Una escalera con las cinco cartas<FF03>del mismo palo!"),
    ("Five of a kind<0006><FF03>Four of a kind with a Joker for the<FF03>fifth card!", "Repoker<0006><FF03>Cuatro iguales con un Joker de<FF03>quinta carta!"),
    ("Royal flush<0006><FF03>A straight flush with 10-J-Q-K-A!", "Escalera real<0006><FF03>Escalera de color con 10-J-Q-K-A!"),
    ("<0039>Special cases<003A>", "<0039>Casos especiales<003A>"),
    ("-In this version of poker, a pair is<FF03>not a winning hand!", "-En esta version de poker, un par no<FF03>es mano ganadora!"),
    ("-In a straight, an ace is not lower<FF03>than a 2!", "-En una escalera, el as no es menor<FF03>que un 2!"),
    ("-The Joker is a wild card that can be<FF03>used as part of any winning hand!", "-El Joker es comodin y sirve en<FF03>cualquier mano ganadora!"),
    # blackjack
    ("It's a video blackjack machine!", "Es una maquina de video blackjack!"),
    ("This is a one-on-one-game of blackjack<FF03>against the dealer!", "Es un juego de blackjack uno a uno<FF03>contra la banca!"),
    ("The computer acts as the dealer!", "La computadora es la banca!"),
    ("Two cards are dealt to the player and<FF03>the dealer at the outset!", "Se reparten dos cartas al jugador y a<FF03>la banca al inicio!"),
    ("One of the dealer's two cards will be<FF03>kept face-down!", "Una de las dos cartas de la banca<FF03>queda boca abajo!"),
    ("If the dealer's shown card is an ace,<FF03>you may place an insurance bet!", "Si la carta visible de la banca es as,<FF03>puedes apostar un seguro!"),
    ("The insurance mechanic will be explained<FF03>at the end of these rules!", "La mecanica del seguro se explica<FF03>al final de estas reglas!"),
    ("First, compare your cards to the dealer's<FF03>to decide whether to draw another card!", "Primero compara tus cartas con las de<FF03>la banca para decidir si pides otra!"),
    ("If you decide to draw, select Hit!<FF03>If not, select Stand!", "Si decides pedir, elige Hit!<FF03>Si no, elige Stand!"),
    ("You may draw up to 7 cards as long as<FF03>their total value remains 21 or lower!", "Puedes pedir hasta 7 cartas mientras<FF03>su total sea 21 o menos!"),
    ("The following circumstances will result<FF03>in an automatic Stand<0006>", "Las siguientes situaciones causan un<FF03>Stand automatico<0006>"),
    ("-Your initial draw is blackjack!", "-Tu mano inicial es blackjack!"),
    ("-The total of the cards drawn after<FF03>Hitting is 21!", "-El total de las cartas tras<FF03>pedir es 21!"),
    ("-You draw seven cards!", "-Sacas siete cartas!"),
    ("-The cards' total value surpasses 21,<FF03>resulting in a bust!", "-El total de las cartas supera 21,<FF03>te pasas!"),
    ("2 through 10 are face value! J through<FF03>K are worth 10, and A is worth either<FF03>1 or 11!", "2 a 10 valen su numero! J a<FF03>K valen 10, y A vale<FF03>1 u 11!"),
    ("After the player Stands, the dealer<FF03>will draw cards!", "Tras el Stand del jugador, la banca<FF03>pide cartas!"),
    ("If your total is larger than the<FF03>dealer's without surpassing 21", "Si tu total supera al de la<FF03>banca sin pasarte de 21"),
    ("The insurance bet will pay out at<FF03>3 to 1, and the game will end!", "El seguro paga<FF03>3 a 1, y el juego termina!"),
    ("If the dealer's card is A through 9,<FF03>the insurance is lost and the game<FF03>progresses normally!", "Si la carta de la banca es A a 9,<FF03>el seguro se pierde y el juego<FF03>sigue normal!"),
    ("Call Hit to draw a card!", "Pide Hit para sacar carta!"),
    ("Call Stand to end your turn!", "Pide Stand para terminar tu turno!"),
    ("Call Double Down!", "Pide Double Down!"),
    ("Call Split when possible!", "Pide Split cuando se pueda!"),
    ("<0044> Winning the game<FF03>If your hand is larger than the dealer's<FF03>without going over 21", "<0044> Ganar el juego<FF03>Si tu mano supera a la de la banca<FF03>sin pasar de 21"),
    ("If you have blackjack of A and J<FF03>and the cards' suit is ", "Si tienes blackjack de A y J<FF03>y el palo es "),
    (", or <0205>!", ", o <0205>!"),
    ("777<0006><FF03>When both initial cards are 7s and you<FF03>draw a third 7 after Hitting!", "777<0006><FF03>Si las dos cartas iniciales son 7 y<FF03>sacas un tercer 7 tras Hit!"),
    # slot
    ("It's a slot machine!", "Es una maquina tragamonedas!"),
    ("This slot machine consists of 5<FF03>big reels and 16 small reels!", "Esta tragamonedas tiene 5<FF03>rodillos grandes y 16 chicos!"),
    ("The number of ways to line up a win<FF03>increases with the size of your bet!", "Las formas de alinear un premio<FF03>aumentan con tu apuesta!"),
    ("You can bet up to 8 coins!", "Puedes apostar hasta 8 monedas!"),
    ("Bets 1, 2, 5, and 6 are for the<FF03>horizontal lines,while 3, 4, 7,<FF03>and 8 are for the vertical lines!", "Apuestas 1, 2, 5 y 6 son lineas<FF03>horizontales, y 3, 4, 7,<FF03>y 8 son verticales!"),
    ("Bets 5 through 8 also add two ways<FF03>to line up a win per bet!", "Apuestas 5 a 8 dan dos formas<FF03>extra de premio cada una!"),
    ("When the game begins, the big and small<FF03>reels will all start to spin!", "Al empezar, los rodillos grandes y<FF03>chicos giran todos!"),
    ("Once the reels have spun enough,<FF03>the small reels will stop! <0029>The big<FF03>reels will continue to spin!<002A>", "Tras girar lo suficiente,<FF03>los rodillos chicos paran! <0029>Los<FF03>grandes siguen girando!<002A>"),
    ("Press the <005B>, <003E>, <0062>, and <0060> buttons to<FF03>rotate the corresponding reels!", "Pulsa <005B>, <003E>, <0062> y <0060> para<FF03>girar los rodillos correspondientes!"),
    ("Adjust the small reels so that it will<FF03>be easier to line up a pattern!", "Ajusta los rodillos chicos para que<FF03>sea mas facil formar un patron!"),
    ("When you have finished, press the<FF03>R button to stop the big reels!", "Cuando termines, pulsa<FF03>R para parar los rodillos grandes!"),
    ("If three or more of a symbol are lined<FF03>up along one of your bets, you win!", "Si tres o mas simbolos se alinean<FF03>en una de tus apuestas, ganas!"),
    ("Up to five symbols can cross bets 1<FF03>through 4, and up to four can cross<FF03>bets 5 through 8!", "Hasta cinco simbolos cruzan apuestas 1<FF03>a 4, y hasta cuatro cruzan<FF03>apuestas 5 a 8!"),
    ("When the symbols on the big reels match<FF03>diagonally, in all four corners, or all<FF03>five at once", "Cuando los simbolos grandes coinciden<FF03>en diagonal, en las cuatro esquinas, o<FF03>las cinco a la vez"),
    ("You win regardless of which lines you<FF03>bet on!", "Ganas sin importar en que lineas<FF03>apostaste!"),
    ("Earnings for hits on the big reels<FF03>increase according to the number of<FF03>bets you made!", "Las ganancias en los rodillos grandes<FF03>aumentan segun el numero de<FF03>apuestas hechas!"),
    ("Rotate the four small reels to the<FF03>bottom!", "Gira los cuatro rodillos chicos<FF03>abajo!"),
    ("Rotate the four small reels to the<FF03>right!", "Gira los cuatro rodillos chicos a la<FF03>derecha!"),
    ("Rotate the four small reels to the top!", "Gira los cuatro rodillos chicos arriba!"),
    ("Rotate the four small reels to the left!", "Gira los cuatro rodillos chicos a la izquierda!"),
    ("Stop the big reels!", "Para los rodillos grandes!"),
    ("Different slot machines have different<FF03>patterns and odds!", "Distintas tragamonedas tienen distintos<FF03>patrones y probabilidades!"),
    ("It's best to try out different machines<FF03>rather than concentrating on one!", "Conviene probar varias maquinas<FF03>en vez de quedarte en una!"),
    ("Be careful not to forget to rotate the<FF03>small reels during the game!", "No olvides girar los<FF03>rodillos chicos durante el juego!"),
    ("Careful adjustment of the small reels<FF03>is key to maximizing your payout!", "Ajustar bien los rodillos chicos<FF03>es clave para maximizar el pago!"),
    ("If you begin the game with fewer bets,<FF03>you may face greater losses when it<FF03>matters most!", "Si empiezas con pocas apuestas,<FF03>podrias perder mas cuando<FF03>mas importa!"),
    ("For best results, always play the game<FF03>with the full eight bets!", "Para mejor resultado, juega siempre<FF03>con las ocho apuestas!"),
    # dice
    ("It's a video dice game!", "Es un juego de dados!"),
    ("In this game, two dice are rolled on<FF03>screen, and you predict the outcome!", "Aqui se lanzan dos dados en<FF03>pantalla y predices el resultado!"),
    ("You can bet on eleven rolls, from 2<FF03>to 12, and you may bet on as many rolls<FF03>per game as you wish!", "Apuestas a once tiros, del 2<FF03>al 12, y a cuantos tiros<FF03>quieras por juego!"),
    ("However, you may bet a maximum of 100<FF03>coins on any given roll!", "Pero apuestas hasta 100<FF03>monedas por tiro!"),
    ("If you bet on the correct roll, a<FF03>multiplier determines your winnings!", "Si aciertas el tiro, un<FF03>multiplicador define tu premio!"),
    ("You can also stake your winnings on<FF03>an Extra Game!", "Tambien puedes apostar tu premio en<FF03>un Juego Extra!"),
    ("In the Extra Game, you do not predict<FF03>the outcome of the roll", "En el Juego Extra no predices<FF03>el resultado del tiro"),
    ("Instead, any roll other than 7 wins!", "En cambio, gana cualquier tiro menos 7!"),
    ("The amount you win differs depending on<FF03>the roll!", "Lo que ganas depende del<FF03>tiro!"),
    ("If the roll is 7, the Extra Game ends<FF03>and all your winnings are lost, so be<FF03>careful!", "Si sale 7, el Juego Extra termina<FF03>y pierdes todo tu premio, ten<FF03>cuidado!"),
    ("Add 10 coins to the bet at the cursor!", "Agrega 10 monedas a la apuesta!"),
    ("Add 100 coins to the bet at the cursor!", "Agrega 100 monedas a la apuesta!"),
    ("Remove all coins at the cursor!", "Quita todas las monedas del cursor!"),
    ("Add a coin to the bet!", "Agrega una moneda a la apuesta!"),
    ("Remove a coin from the bet!", "Quita una moneda de la apuesta!"),
    ("Try the Extra Game again!", "Prueba el Juego Extra otra vez!"),
    ("Try the Extra Game!", "Prueba el Juego Extra!"),
    ("Select the rolls to bet on!", "Elige los tiros a apostar!"),
    ("The closer the roll is to 7, the lower<FF03>the multiplier! This is because rolls<FF03>close to 7 appear more frequently!", "Mientras mas cerca de 7, menor<FF03>el multiplicador! Los tiros<FF03>cerca de 7 salen mas seguido!"),
    ("Thus, the safe bet is on rolls close<FF03>to 7, with rolls like 2 and 12 being<FF03>riskier!", "Lo seguro es apostar a tiros<FF03>cerca de 7; los como 2 y 12 son<FF03>mas riesgosos!"),
    ("In the Extra Game, if a roll of 7<FF03>comes up, you lose all your winnings!", "En el Juego Extra, si sale un 7,<FF03>pierdes todo tu premio!"),
    ("The trick to not losing too much is<FF03>not to get greedy and leave with a<FF03>reasonable amount!", "El truco es no ser avido y<FF03>retirarte con una<FF03>cantidad razonable!"),
    # code breaker
    ("You have <FF1A><8200> Metal Cards!", "Tienes <FF1A><8200> Metal Cards!"),
    ("It's a Code Breaker machine!", "Es una maquina Code Breaker!"),
    ("In this game, the numbers 1 through 9<FF03>are dispersed throughout a grid!", "Aqui los numeros del 1 al 9<FF03>se reparten en una cuadricula!"),
    ("Your goal is to guess the arrangement<FF03>of the numbers!", "Tu meta es adivinar el orden<FF03>de los numeros!"),
    ("The fewer tries it takes, the better<FF03>the prize you receive!", "Mientras menos intentos, mejor<FF03>el premio que recibes!"),
    ("If you cannot crack it in 8 tries,<FF03>the game ends!", "Si no lo resuelves en 8 intentos,<FF03>el juego termina!"),
    ("The Result to the left of the screen<FF03>shows your previous attempts!", "El Resultado a la izquierda<FF03>muestra tus intentos previos!"),
    ("If you guess incorrectly, the guess<FF03>will be displayed in the Results!", "Si fallas, el intento<FF03>se muestra en los Resultados!"),
    ("Use it as a reference when formulating<FF03>your next guess!", "Usalo de referencia al formular<FF03>tu siguiente intento!"),
    ("The Chosen display at the top shows<FF03>the numbers in use!", "La pantalla Elegidos arriba muestra<FF03>los numeros en uso!"),
    ("All numbers, 1 through 9, must be used<FF03>in the code!", "Todos los numeros, 1 al 9, van<FF03>en el codigo!"),
    ("Use the Chosen display to see which<FF03>numbers are missing from your guess!", "Usa Elegidos para ver que<FF03>numeros faltan en tu intento!"),
    ("This game accepts <FF18><0700>Metal Cards<FF18>  instead<FF03>of coins!", "Este juego acepta <FF18><0700>Metal Cards<FF18>  en vez<FF03>de monedas!"),
    ("Decreases the selected number!", "Baja el numero elegido!"),
    ("Increases the selected number!", "Sube el numero elegido!"),
    ("Marks the selected number by changing<FF03>its color!", "Marca el numero elegido cambiando<FF03>su color!"),
    ("Use this to mark numbers you know are<FF03>correct!", "Usalo para marcar numeros que sabes<FF03>correctos!"),
    ("Inserts 1 Metal Card to start the game!", "Mete 1 Metal Card para empezar!"),
    ("Quit the game!", "Sal del juego!"),
    ("Moves the cursor!", "Mueve el cursor!"),
    ("H indicates how many exact matches<FF03>are in a row<001E>column!", "H indica cuantos aciertos exactos<FF03>hay en fila<001E>columna!"),
    ("B shows how many numbers belong in<FF03>that row<001E>column, but not in their<FF03>present position!", "B indica cuantos numeros van en<FF03>esa fila<001E>columna, pero no en su<FF03>posicion actual!"),
    ("The key to the game is to determine<FF03>where a hit <0029>H<002A> is on both the row<FF03>and the column!", "La clave es determinar<FF03>donde un acierto <0029>H<002A> esta en fila<FF03>y columna!"),
    ("It's best to mark places where both<FF03>the row and the column are hits!", "Conviene marcar donde fila<FF03>y columna son aciertos!"),
    ("The Results of your previous guesses<FF03>can also be useful hints!", "Los Resultados previos<FF03>tambien dan buenas pistas!"),
    ("Select a card!", "Elige una carta!"),
    ("Select cards!", "Elige cartas!"),
    # shared menu
    ("You currently have <FF11> coins!", "Tienes <FF11> monedas!"),
    ("You have <FF11> coins!", "Tienes <FF11> monedas!"),
    ("It's a video poker machine!", "Es una maquina de video poker!"),
    ("What will you do?", "Que haras?"),
    ("What would you like explained?", "Que quieres que te explique?"),
    # section labels (generic, last)
    ("<0043>Before normal play<0044>", "<0043>Antes del juego normal<0044>"),
    ("<0043>During normal play<0044>", "<0043>Durante el juego normal<0044>"),
    ("<0043>After winning hand<0044>", "<0043>Tras mano ganadora<0044>"),
    ("<0043>During Extra Game<0044>", "<0043>Durante Juego Extra<0044>"),
    ("<0043>After winning the Extra Game<0044>", "<0043>Tras ganar el Juego Extra<0044>"),
    ("<0043>After winning Extra Game<0044>", "<0043>Tras ganar Juego Extra<0044>"),
    ("<0043>After winning<0044>", "<0043>Tras ganar<0044>"),
    ("<0043>Before starting<0044>", "<0043>Antes de empezar<0044>"),
    ("<0043>During play<0044>", "<0043>Durante el juego<0044>"),
    ("Add a coin!", "Agrega una moneda!"),
    ("Remove a coin!", "Quita una moneda!"),
    ("Bet the maximum total possible!", "Apuesta el maximo total posible!"),
    ("Reset bet amount to 0 coins!", "Reinicia la apuesta a 0 monedas!"),
    ("Starts the game if a bet has been placed!", "Inicia el juego si hay apuesta!"),
    ("Ends the game if no bet has been placed!", "Termina el juego si no hay apuesta!"),
    ("Ends the game!", "Termina el juego!"),
    ("Directional buttons<003A>", "Botones direccionales<003A>"),
    (" Button<003A>", " boton<003A>"),
    (" button<003A>", " boton<003A>"),
    ("Not used!", "Sin uso!"),
]

IDS = ["e0_00175", "e0_00176", "e0_00183", "e0_00184", "e0_00185"]
for i in IDS:
    s = W.O(i)
    for en, es in PAIRS:
        if en in s:
            s = s.replace(en, es)
    W._M[i] = {"t": s, "shortened": True}
W.dump(os.path.join(os.path.dirname(__file__), "e0_casino.json"))
